language: generic
sudo: required
services:
  - docker

# Build the development file for testing
before_install:
  - docker build -t codeballet/react-test -f ./client/Dockerfile.dev ./client

# Run tests
script:
  - docker run -e CI=true codeballet/react-test npm test

after_success:
  # Build the images with the production Dockerfile
  - docker build -t codeballet/multi-docker-client ./client
  - docker build -t codeballet/multi-docker-nginx ./nginx
  - docker build -t codeballet/multi-docker-server ./server
  - docker build -t codeballet/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push codeballet/multi-docker-client
  - docker push codeballet/multi-docker-nginx
  - docker push codeballet/multi-docker-server
  - docker push codeballet/multi-docker-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-1-442971121200"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_ACCESS_KEY
